In [2]:
!pip install pandas

Requirement already satisfied: pandas in /home/leandro/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /home/leandro/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/leandro/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/leandro/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/leandro/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/leandro/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import os
from IPython.display import HTML

A biblioteca `os`do Python oferece um conjunto de funções que permite interagir com o sistema operacional para realizar tarefas como manipulação de arquivos e diretórios, obtenção de informações do sistema, etc.

Neste segundo projeto, além de análise de vendas, o foco se estende para a qualificação e visualização de devoluções e sazonalidade. Utiliza estruturas de repetição para consolidar dados de multiplas planilhas e empregaa biblioteca plotly para gráfico mais interativos e customizados, como gráficos de pizza e histogramas. Também introduz a análise temporal, com resample de dados mensais e cálculo de variações.

- Passo 1 -> importar as bibliotecas necessárias
- passo 2 -> percorrer todos os arquivos (panilhas) existentes dentro de uma pasta no google drive
- passo 3 -> importar todos os arquivos (panilhas) de vendas e unificá-las numa única tabela (DataFrame) no Pandas
- passo 4 -> importar todos os arquivos (panilhas) de devoluções e unificá-las numa única tabela (DataFrame) no Pandas

###Indicadores

1.0 - Quantidade de vendas líquidas:
Objetivo: identificar os 3 produtos e as 3 lojas que estão gerando mais vendas

1.1 - Quantidade de vendas brutas:
objetivo: identificar os 3 produtos e as 3 lojas que estão gerando mais vendas

1.2 - Quantidade de devoluções:
objetivo: identificar os 3 produtos e as 3 lojas que estão gerando mais devoluções

2.0 - Análise de sazonalidade

In [4]:
#passo 2 -> percorrer todos os arquivos (panilhas) existentes dentro de uma pasta no google drive
lista_planilhas = os.listdir('./dados')

O método `listdir()`é utilizado para listar todos os arquivos e diretórios no diretório especificado.

In [5]:
display(lista_planilhas)

['Devolucoes+-+Fortaleza.csv',
 'Vendas+-+Recife.csv',
 'Vendas+-+Rio+de+Janeiro.csv',
 'Devolucoes+-+Salvador.csv',
 'Vendas+-+Goiás.csv',
 'Vendas+-+Salvador.csv',
 'Vendas+-+Curitiba.csv',
 'Vendas+-+Porto+Alegre.csv',
 'Devolucoes+-+Porto+Alegre.csv',
 'Devolucoes+-+Recife.csv',
 'Devolucoes+-+Rio+de+Janeiro.csv',
 'Vendas+-+Fortaleza.csv',
 'Devolucoes+-+São+Paulo.csv',
 'Devolucoes+-+Curitiba.csv',
 'Vendas+-+Belo+Horizonte.csv',
 'Devolucoes+-+Belo+Horizonte.csv',
 'Vendas+-+São+Paulo.csv',
 'Devolucoes+-+Goiás.csv']

####O que são estruturas de repetição ou loops

As estruturas de repetição ou loops são recursos daslinguagens de programação responsáveis por executar um bloco de código repetidamente através de determinadas condições específicas. O Python contêm dois tipos de estruturas de repetição: `for` e `While`.

####For

Usado para iterar sobre uma sequência de dados, como: listas, dicinoários, conjuntos ou executar um bloco de código para cada elemento da sequência.

for variavel_temporaria in sequencia:
    bloco de código a ser executado para cada elemento da sequência

####While

Também pode ser usado para iterar nestas estruturas de dados, a execução ocorre enquanto uma condição especificada for verdadeira.

while condicao:
    bloco de código a ser executado enquanto a condição for verdadeira

####Listas (list)

Listas são coleções ordenadas e mutáveis de elementos. Os elementos podem ser de qualquer tipo, incluindo outras listas.

In [6]:
minha_lista = [1, 2, 3, 'a', 'b']

In [7]:
#Exemplo (for)
lista_nomes = ['João', 'Maria', 'Pedro']

for nome in lista_nomes:
    print(f'Olá, {nome}!')

Olá, João!
Olá, Maria!
Olá, Pedro!

In [8]:
#Exemplo (while)
lista_nomes = ['João', 'Maria', 'Pedro']
indice = 0

while indice < len(lista_nomes):
    print(f'Olá, {lista_nomes[indice]}!')
    indice += 1

Olá, João!
Olá, Maria!
Olá, Pedro!

####Tuplas (Tuple)

Tuplas são semelhantes às listas, mas são imutáveis, o que significa que seus elementos não podem ser alterados após a criação da tupla

In [9]:
minha_tupla = (1,2,3)

In [10]:
#Exemplo For
dias_da_semana = ('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo')
for dia in dias_da_semana:
    print(f'Hoje é {dia}')

Hoje é Segunda
Hoje é Terça
Hoje é Quarta
Hoje é Quinta
Hoje é Sexta
Hoje é Sábado
Hoje é Domingo

In [11]:
#Exemplo While
indice = 0

while indice < len(dias_da_semana):
    print(f'Hoje é {dias_da_semana[indice]}')
    indice += 1

Hoje é Segunda
Hoje é Terça
Hoje é Quarta
Hoje é Quinta
Hoje é Sexta
Hoje é Sábado
Hoje é Domingo

`Incremento de variável` é o processo de aumentar o valor de uma variável por um determinado montante. Geralmente usado em algumas estruturas de repetição

####Conjuntos (set)

Conjuntos são coleções não ordenadas de elementos únicos. Os conjuntos são úteis para eliminar elementos duplicados e realizar operações de teoria dos conjuntos como união, interseção, etc.

In [12]:
meu_conjunto = {1,2,3,4}

In [13]:
#Exemplo for
frutas = {'maça', 'banana', 'laranja', 'maça', 'pera'}
for fruta in frutas:
    print(fruta)

banana
maça
laranja
pera

In [14]:
#Exemplo while
lista_frutas = list(frutas)
indice = 0

while indice < len(lista_frutas):
    print(lista_frutas[indice])
    indice += 1

banana
maça
laranja
pera

####Dicionários (dict)

Dicionários são coleções não ordenadas de pares chave-fechadura. Eles são mutáveis e as chaves devem ser únicas e imutáveis.

In [15]:
meu_discionario = {'nome': 'João', 'idade': 30}

In [16]:
#Exemplo for
alunos_idade = {'Maria': 20, 'João': 21, 'Pedro': 22}
for aluno, idade in alunos_idade.items():
    print(f'{aluno} tem {idade} anos')

Maria tem 20 anos
João tem 21 anos
Pedro tem 22 anos

In [17]:
#Exemplo while
chaves = list(alunos_idade.keys())
valores = list(alunos_idade.values())
indice = 0

while indice < len(chaves):
    aluno = chaves[indice]
    idade = valores[indice]
    print(f'{aluno} tem {idade} anos')
    indice += 1

Maria tem 20 anos
João tem 21 anos
Pedro tem 22 anos

####Strings (str)
Embora não sejam frequentemente descritas como estruturas de dados, as strings em Python são, na prática, sequências imutáveis de caracteres e suportam uma variedade de operações que você pode realizar com sequências.

In [18]:
minha_string = 'Olá, Mundo!'

In [19]:
#Exemplo for
palavra = 'Python'
for letra in palavra:
    print(letra)

P
y
t
h
o
n

In [20]:
#Exemplo while
indice = 0

while indice < len(palavra):
    print(palavra[indice])
    indice += 1

P
y
t
h
o
n

####Estruturas Condicionais

Uma `Estrutura Condicinal` na programação permite que um programa execute diferentes ações com base emuma condição específica, desviando o fluxo do programa confirme necessário.


As estruturas condicionais são usadas para determinar qual bloco de código será executado a partir de uma determinada condição. O Python disponibiliza 3 comandos que ajudam a comandar o fluxo de execução, sendo: if, elif e else

if condicao1:
    bloco de código executado se condicao1 for verdadeira
elif condicao2:
    bloco de código executado se condicao1 for falsa e condicao2 for verdadeira
else:
    bloco de código executado se nenhuma das condições acima for verdadeira

In [21]:
#if: Este é o mais básico e é utilizado para executar um bloco de código apenas se uma determinada condição for verdadeira

a = 10
b = 5

if a > b:
    print('a é maior que b')

a é maior que b

In [22]:
#elif: É utilizado para testar múltiplas condições após o if inicial. Se a condição no if inicial for falsa, o Python verifica a condição no elif

a = 10
b = 15 
c = 5

if a > b:
    print('a é maior que b')
elif a >= c:
    print('a é maior que c mas menor ou igual a b')

a é maior que c mas menor ou igual a b

In [23]:
#else: Este bloco será executado se nenhuma das condições anteriores (no if ou elif) for verdadeira

a = 1
b = 15 
c = 5

if a > b:
    print('a é maior que b')
elif a >= c:
    print('a é maior que 5 mas menor ou igual ao b')
else:
    print('a é menor ou igual ao b')

a é menor ou igual ao b

In [24]:
for planilha in lista_planilhas:
    if 'Vendas' in planilha:
        print(planilha)

Vendas+-+Recife.csv
Vendas+-+Rio+de+Janeiro.csv
Vendas+-+Goiás.csv
Vendas+-+Salvador.csv
Vendas+-+Curitiba.csv
Vendas+-+Porto+Alegre.csv
Vendas+-+Fortaleza.csv
Vendas+-+Belo+Horizonte.csv
Vendas+-+São+Paulo.csv

In [25]:
for planilha in lista_planilhas:
    if 'Vendas' in planilha:
        print(f'./dados/{planilha}')

./dados/Vendas+-+Recife.csv
./dados/Vendas+-+Rio+de+Janeiro.csv
./dados/Vendas+-+Goiás.csv
./dados/Vendas+-+Salvador.csv
./dados/Vendas+-+Curitiba.csv
./dados/Vendas+-+Porto+Alegre.csv
./dados/Vendas+-+Fortaleza.csv
./dados/Vendas+-+Belo+Horizonte.csv
./dados/Vendas+-+São+Paulo.csv

In [26]:
for planilha in lista_planilhas:
    if 'Vendas' in planilha:
        tabelas = pd.read_csv(f'./dados/{planilha}')
        display(tabelas)

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,1,HL4379,Televisão,3,Renan,Nascimento,9/14/2023,Recife,2500,NaN
1,24,HL2714,Tablet,5,Carla,Zakhm,11/13/2023,Recife,1600,NaN
2,26,HL1918,iPhone,4,Bianca,Tatsch,10/10/2023,Recife,5300,NaN
3,35,HL1918,iPhone,3,Guido,Monteiro,4/18/2023,Recife,5300,NaN
4,44,HL4379,Televisão,1,Eduardo,Quindeler,7/20/2023,Recife,2500,NaN
...,...,...,...,...,...,...,...,...,...,...
720,9938,HL4379,Televisão,3,Fernanda,Silva,12/18/2023,Recife,2500,NaN
721,9941,HL2714,Tablet,5,Alvaro,Kranz,11/21/2023,Recife,1600,NaN
722,9969,HL1918,iPhone,4,Itai,Puntel,11/6/2023,Recife,5300,NaN
723,9986,HL9962,Android,4,Julia,Leite,4/8/2023,Recife,3400,NaN
724,9992,HL1918,iPhone,1,Marina,Cormack,12/31/2023,Recife,5300,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,8,HL4379,Televisão,4,Jessica,Cordovil,2/11/2023,Rio de Janeiro,2500,NaN
1,12,HL1918,iPhone,2,Camilla,Guimaríes,10/4/2023,Rio de Janeiro,5300,NaN
2,21,HL4379,Televisão,5,Katharina,Barros,3/26/2023,Rio de Janeiro,2500,NaN
3,39,HL9962,Android,1,Rodrigo,Silva,1/14/2023,Rio de Janeiro,3400,NaN
4,41,HL4379,Televisão,3,Júlio,Freire,6/30/2023,Rio de Janeiro,2500,NaN
...,...,...,...,...,...,...,...,...,...,...
1462,9971,HL1918,iPhone,4,Isaac,Santos,12/3/2023,Rio de Janeiro,5300,NaN
1463,9976,HL9962,Android,2,Andreza,Ramos,12/17/2023,Rio de Janeiro,3400,NaN
1464,9982,HL4379,Televisão,3,Leticia,Mesquita,5/22/2023,Rio de Janeiro,2500,NaN
1465,9987,HL1918,iPhone,5,Manuela,Merege,9/12/2023,Rio de Janeiro,5300,NaN
1466,9989,HL1918,iPhone,5,Rafael,Carneiro,2/28/2023,Rio de Janeiro,5300,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,13,HL4379,Televisão,1,Daniel,Monteiro,5/23/2023,Goiás,2500,NaN
1,19,HL9962,Android,4,Elaine,Santos,7/5/2023,Goiás,3400,NaN
2,45,HL1918,iPhone,5,Lenon,Fernandes,3/31/2023,Goiás,5300,NaN
3,50,HL7348,SmartWatch,1,Vivianne,Rodrigues,8/11/2023,Goiás,1400,NaN
4,97,HL7348,SmartWatch,2,Pedro,Rodrigues,7/26/2023,Goiás,1400,NaN
...,...,...,...,...,...,...,...,...,...,...
727,9925,HL1918,iPhone,2,Victor,Gomes,1/9/2023,Goiás,5300,NaN
728,9937,HL8851,Notebook,2,Gabriel,Ribeiro,11/28/2023,Goiás,3500,NaN
729,9943,HL2714,Tablet,2,Giuseppe,Borges,10/5/2023,Goiás,1600,NaN
730,9968,HL2714,Tablet,2,Caio,Caldas,4/4/2023,Goiás,1600,NaN
731,9975,HL8851,Notebook,2,Anna,Maia,10/22/2023,Goiás,3500,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,40,HL1148,Câmera,2,Gabriel,Almeida,11/16/2023,Salvador,2100,NaN
1,42,HL2714,Tablet,5,Rodrigo,Alves,2/27/2023,Salvador,1600,NaN
2,51,HL1918,iPhone,4,Ulisses,Arruda,5/5/2023,Salvador,5300,NaN
3,70,HL9962,Android,3,Raissa,Negrelli,3/10/2023,Salvador,3400,NaN
4,94,HL1918,iPhone,2,Breno,Caputo,3/30/2023,Salvador,5300,NaN
...,...,...,...,...,...,...,...,...,...,...
1325,9965,HL1148,Câmera,4,Samara,Pinto,3/11/2023,Salvador,2100,NaN
1326,9970,HL9962,Android,1,Fernanda,Junior,9/12/2023,Salvador,3400,NaN
1327,9972,HL1918,iPhone,4,Helena,Chafin,8/10/2023,Salvador,5300,NaN
1328,9988,HL1918,iPhone,1,Aline,Morais,5/23/2023,Salvador,5300,NaN
1329,9990,HL8851,Notebook,2,Raí­ssa,Oros,5/20/2023,Salvador,3500,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,0,HL4379,Televisão,5,Gabriel,Thoni,6/30/2023,Curitiba,2500,NaN
1,7,HL2714,Tablet,2,Thays,Castro,3/7/2023,Curitiba,1600,NaN
2,22,HL1918,iPhone,3,Lucas,Rodrigues,10/8/2023,Curitiba,5300,NaN
3,28,HL1918,iPhone,3,Gabriel,Silva,8/21/2023,Curitiba,5300,NaN
4,59,HL4379,Televisão,3,Pedro,Conceiçío,5/16/2023,Curitiba,2500,NaN
...,...,...,...,...,...,...,...,...,...,...
714,9859,HL2714,Tablet,1,Júlio,Fraga,12/25/2023,Curitiba,1600,NaN
715,9876,HL4379,Televisão,5,Bruno,Mota,4/30/2023,Curitiba,2500,NaN
716,9918,HL1148,Câmera,2,Lucas,Reis,12/27/2023,Curitiba,2100,NaN
717,9944,HL1918,iPhone,5,Raphael,Kurtz,7/16/2023,Curitiba,5300,NaN
718,9998,HL7348,SmartWatch,1,Viní­cius,Antunes,12/10/2023,Curitiba,1400,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,14,HL4379,Televisão,4,Ylana,Teraoka,6/23/2023,Porto Alegre,2500,NaN
1,34,HL1148,Câmera,1,Rubens,Netto,7/11/2023,Porto Alegre,2100,NaN
2,43,HL1148,Câmera,5,Paloma,Sperandei,9/15/2023,Porto Alegre,2100,NaN
3,49,HL8851,Notebook,5,Breno,Farias,6/24/2023,Porto Alegre,3500,NaN
4,52,HL4379,Televisão,2,Lorena,Kohn,7/31/2023,Porto Alegre,2500,NaN
...,...,...,...,...,...,...,...,...,...,...
699,9947,HL1918,iPhone,2,Gabrielle,Vasconcelos,2/20/2023,Porto Alegre,5300,NaN
700,9980,HL1918,iPhone,5,Joío,Rodrigues,1/21/2023,Porto Alegre,5300,NaN
701,9983,HL2714,Tablet,5,Bianca,Tatsch,2/12/2023,Porto Alegre,1600,NaN
702,9993,HL1148,Câmera,4,Victor,Lira,7/26/2023,Porto Alegre,2100,NaN
703,9997,HL1918,iPhone,4,Norman,Jimbo,6/13/2023,Porto Alegre,5300,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,2,HL1148,Câmera,2,Camila,Sobral,10/21/2023,Fortaleza,2100,NaN
1,3,HL1918,iPhone,3,Clara,Bruno,7/8/2023,Fortaleza,5300,NaN
2,4,HL9962,Android,4,Eduardo,Pacheco,12/19/2023,Fortaleza,3400,NaN
3,11,HL1918,iPhone,2,Rafael,Rocha,12/22/2023,Fortaleza,5300,NaN
4,15,HL2714,Tablet,2,Caio,Ferreira,7/26/2023,Fortaleza,1600,NaN
...,...,...,...,...,...,...,...,...,...,...
1442,9959,HL1918,iPhone,4,Rafael,Carneiro,6/19/2023,Fortaleza,5300,NaN
1443,9974,HL1148,Câmera,2,Thales,Gouvêa,2/20/2023,Fortaleza,2100,NaN
1444,9979,HL1918,iPhone,5,Brenno,Santos,10/18/2023,Fortaleza,5300,NaN
1445,9994,HL4379,Televisão,2,Caio,Ferreira,5/18/2023,Fortaleza,2500,NaN
1446,9995,HL1148,Câmera,5,Kim,Ferreira,3/6/2023,Fortaleza,2100,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,17,HL4379,Televisão,2,Carolina,Alfradique,2/25/2023,Belo Horizonte,2500,NaN
1,25,HL4379,Televisão,1,Danilo,Rubim,2/20/2023,Belo Horizonte,2500,NaN
2,27,HL1918,iPhone,5,Bernard,Pedrosa,7/7/2023,Belo Horizonte,5300,NaN
3,54,HL1918,iPhone,5,Lucas,Lemos,12/26/2023,Belo Horizonte,5300,NaN
4,67,HL8851,Notebook,5,Bernardo,Botelho,6/8/2023,Belo Horizonte,3500,NaN
...,...,...,...,...,...,...,...,...,...,...
644,9910,HL1148,Câmera,4,Norman,Jimbo,2/17/2023,Belo Horizonte,2100,NaN
645,9927,HL2714,Tablet,2,Marina,Marins,1/29/2023,Belo Horizonte,1600,NaN
646,9932,HL1918,iPhone,1,José,Vieira,5/11/2023,Belo Horizonte,5300,NaN
647,9942,HL4379,Televisão,1,Fernanda,Junior,2/9/2023,Belo Horizonte,2500,NaN
648,9978,HL8851,Notebook,2,Mariane,Racy,12/28/2023,Belo Horizonte,3500,NaN

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,5,HL1918,iPhone,4,Sarah,Souza,2/14/2023,São Paulo,5300,NaN
1,6,HL7348,SmartWatch,3,Alexandre,Rodriguez,5/20/2023,São Paulo,1400,NaN
2,9,HL1148,Câmera,3,Camille,Silva,3/26/2023,São Paulo,2100,NaN
3,10,HL1918,iPhone,3,Alon,Palmeira,11/6/2023,São Paulo,5300,NaN
4,18,HL8851,Notebook,4,Leandro,Rodrigues,8/6/2023,São Paulo,3500,NaN
...,...,...,...,...,...,...,...,...,...,...
2221,9981,HL7348,SmartWatch,4,Joío,Junior,4/14/2023,São Paulo,1400,NaN
2222,9984,HL1918,iPhone,4,Itai,Puntel,5/2/2023,São Paulo,5300,NaN
2223,9985,HL1918,iPhone,1,Guilherme,Vianna,3/18/2023,São Paulo,5300,NaN
2224,9991,HL7348,SmartWatch,5,Antônio,Soares,11/21/2023,São Paulo,1400,NaN
2225,9996,HL4379,Televisão,5,Caio,Moraes,1/22/2023,São Paulo,2500,NaN

In [27]:
total_vendas = pd.DataFrame()

for planilha in lista_planilhas:
    if 'Vendas' in planilha:
        tabela = pd.read_csv(f'./dados/{planilha}')
        total_vendas = pd.concat([total_vendas, tabela])

display(total_vendas)

,Unnamed: 0,SKU,Produto,Quantidade,Primeiro Nome,Sobrenome,Data,Loja,Valor Unitário,Unnamed: 8
0,1,HL4379,Televisão,3,Renan,Nascimento,9/14/2023,Recife,2500,NaN
1,24,HL2714,Tablet,5,Carla,Zakhm,11/13/2023,Recife,1600,NaN
2,26,HL1918,iPhone,4,Bianca,Tatsch,10/10/2023,Recife,5300,NaN
3,35,HL1918,iPhone,3,Guido,Monteiro,4/18/2023,Recife,5300,NaN
4,44,HL4379,Televisão,1,Eduardo,Quindeler,7/20/2023,Recife,2500,NaN
...,...,...,...,...,...,...,...,...,...,...
2221,9981,HL7348,SmartWatch,4,Joío,Junior,4/14/2023,São Paulo,1400,NaN
2222,9984,HL1918,iPhone,4,Itai,Puntel,5/2/2023,São Paulo,5300,NaN
2223,9985,HL1918,iPhone,1,Guilherme,Vianna,3/18/2023,São Paulo,5300,NaN
2224,9991,HL7348,SmartWatch,5,Antônio,Soares,11/21/2023,São Paulo,1400,NaN
2225,9996,HL4379,Televisão,5,Caio,Moraes,1/22/2023,São Paulo,2500,NaN

In [28]:
total_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 2225
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9999 non-null   int64
 1   SKU             9999 non-null   object
 2   Produto         9999 non-null   object
 3   Quantidade      9999 non-null   int64
 4   Primeiro Nome   9999 non-null   object
 5   Sobrenome       9999 non-null   object
 6   Data            9999 non-null   object
 7   Loja            9999 non-null   object
 8   Valor Unitário  9999 non-null   int64
 9   Unnamed: 8      0 non-null      float64
dtypes: float64(1), int64(3), object(6)
memory usage: 859.3+ KB

In [29]:
total_devolucoes = pd.DataFrame()

for devolucoes in lista_planilhas:
    if 'Devolucoes' in devolucoes:
        tabela_devolucoes = pd.read_csv(f'./dados/{devolucoes}')
        total_devolucoes = pd.concat([total_devolucoes, tabela_devolucoes])

display(total_devolucoes)

,Unnamed: 0,SKU,Produto,Quantidade,Data,Loja,Valor Unitário,Unnamed: 6
0,4,HL7348,SmartWatch,5,10/7/2023,Fortaleza,1400,NaN
1,8,HL2714,Tablet,3,7/26/2023,Fortaleza,1600,NaN
2,9,HL7348,SmartWatch,2,7/8/2023,Fortaleza,1400,NaN
3,25,HL7348,SmartWatch,3,9/15/2023,Fortaleza,1400,NaN
4,34,HL7348,SmartWatch,3,12/16/2023,Fortaleza,1400,NaN
...,...,...,...,...,...,...,...,...
29,414,HL7348,SmartWatch,3,1/4/2023,Goiás,1400,NaN
30,426,HL1148,Câmera,2,10/1/2023,Goiás,2100,NaN
31,461,HL7348,SmartWatch,2,4/9/2023,Goiás,1400,NaN
32,462,HL4379,Televisão,3,1/12/2023,Goiás,2500,NaN
33,469,HL2714,Tablet,5,2/22/2023,Goiás,1600,NaN

- API é a sigla para 'Application Programming Interface', que em português significa 'Interface de Programação de Aplicações'
- JSON é a sigla para 'JavaScript Object  Notation', é um formato leve de intercâmbio de dados
- Markdown é uma linguagem de marcação leve e que foi projetada para ser fácil de ler e escrever e tornou-se muito popular para documentação, blogs, comentários em fóruns, entre outras aplicações

In [30]:
#Quantidade de vendas líquidas: identificar os 3 produtos e as 3 lojas que estão gerando mais vendas
quant_produto_v1 = total_vendas[['SKU', 'Produto', 'Quantidade']]
display(quant_produto_v1)

         SKU     Produto  Quantidade
0     HL4379   Televisão           3
1     HL2714      Tablet           5
2     HL1918      iPhone           4
3     HL1918      iPhone           3
4     HL4379   Televisão           1
...      ...         ...         ...
2221  HL7348  SmartWatch           4
2222  HL1918      iPhone           4
2223  HL1918      iPhone           1
2224  HL7348  SmartWatch           5
2225  HL4379   Televisão           5

[9999 rows x 3 columns]

In [31]:
quant_produto_v1 = total_vendas[['SKU', 'Produto', 'Quantidade']].groupby(['SKU', 'Produto']).sum().sort_values(by='Quantidade', ascending=False)
display(HTML('Quantidade de Vendas líquidas por produto: '))
display(quant_produto_v1.head(3))

                  Quantidade
SKU    Produto
HL1918 iPhone           8974
HL4379 Televisão        5931
HL8851 Notebook         3249

In [32]:
quant_loja_v1 = total_vendas[['Loja', 'Quantidade']].groupby(['Loja']).sum().sort_values(by='Quantidade', ascending=False)
display(quant_loja_v1.head(3))

                Quantidade
Loja
São Paulo             6674
Rio de Janeiro        4393
Fortaleza             4320

In [33]:
#Quantidade de vendas brutas: identificar os 3 produtos e as 3 lojas que estão gerando mais vendas
quant_produto_valor_bruto = pd.DataFrame(pd.concat([total_vendas, total_devolucoes]).groupby(['SKU', 'Produto'])['Quantidade'].sum()).sort_values(by='Quantidade', ascending=False)
display(quant_produto_valor_bruto.head(3))

                  Quantidade
SKU    Produto
HL1918 iPhone           9144
HL4379 Televisão        6078
HL8851 Notebook         3423

In [34]:
quant_loja_valor_bruto = pd.DataFrame(pd.concat([total_vendas, total_devolucoes]).groupby(['Loja'])['Quantidade'].sum()).sort_values(by='Quantidade', ascending=False)
display(quant_loja_valor_bruto.head(3))

                Quantidade
Loja
São Paulo             6974
Rio de Janeiro        4614
Fortaleza             4591

In [35]:
#Quantidade de devoluções: identificar os 3 produtos e as 3 lojas que estão gerando mais devoluções
quant_produto_dev1 = total_devolucoes[['SKU', 'Produto', 'Quantidade']].groupby(['SKU', 'Produto']).sum().sort_values(by='Quantidade', ascending=False)
display(quant_produto_dev1.head(3))

                   Quantidade
SKU    Produto
HL7348 SmartWatch         395
HL2714 Tablet             301
HL9962 Android            187

In [36]:
quant_loja_dev1 = total_devolucoes[['Loja', 'Quantidade']].groupby('Loja').sum().sort_values(by='Quantidade', ascending=False)
display(quant_loja_dev1.head(3))

                Quantidade
Loja
São Paulo              300
Fortaleza              271
Rio de Janeiro         221

In [37]:
#Análise de sazonalidade: Calcular a variação das vendas dos produtos por mês
total_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 2225
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      9999 non-null   int64
 1   SKU             9999 non-null   object
 2   Produto         9999 non-null   object
 3   Quantidade      9999 non-null   int64
 4   Primeiro Nome   9999 non-null   object
 5   Sobrenome       9999 non-null   object
 6   Data            9999 non-null   object
 7   Loja            9999 non-null   object
 8   Valor Unitário  9999 non-null   int64
 9   Unnamed: 8      0 non-null      float64
dtypes: float64(1), int64(3), object(6)
memory usage: 859.3+ KB

In [38]:
data_format = pd.to_datetime(total_vendas['Data'], format='%m/%d/%Y')
vendas_mensais = pd.DataFrame(
    {
        'Data': data_format,
        'Quantidade': total_vendas['Quantidade']
    }
)

vendas_mensais = vendas_mensais.set_index('Data').resample('M').sum()
vendas_mensais.index = vendas_mensais.index.strftime('%b/%Y')

vendas_mensais['Variacao'] = vendas_mensais['Quantidade'].diff()
display(vendas_mensais)

/tmp/ipykernel_57570/685665052.py:9: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  vendas_mensais = vendas_mensais.set_index('Data').resample('M').sum()

          Quantidade  Variacao
Data
Jan/2023        2553       NaN
Feb/2023        2508     -45.0
Mar/2023        2538      30.0
Apr/2023        2366    -172.0
May/2023        2357      -9.0
Jun/2023        2584     227.0
Jul/2023        2666      82.0
Aug/2023        2400    -266.0
Sep/2023        2446      46.0
Oct/2023        2466      20.0
Nov/2023        2473       7.0
Dec/2023        2686     213.0

NAN é a sigla para 'Not a Number' (não é um número). É a forma que o Pandas e outras bibliotecas no ecossistema Python usam para indicar valores faltantes ou ausentes em um conjunto de dados.

In [39]:
#Análise de faturamento trimestral: Calcular o faturamento trimestral do ano
faturamento_trimestral = pd.DataFrame(
    {
    'Data': data_format,
    'Quantidade': total_vendas['Quantidade'],
    'Valor Unitario':  total_vendas['Valor Unitário'],
    'Faturamento': total_vendas['Quantidade'] * total_vendas['Valor Unitário']
    }
)

faturamento_trimestral['Trimestre'] = faturamento_trimestral['Data'].dt.to_period('Q')
faturamento_trimestral = pd.DataFrame(faturamento_trimestral.groupby('Trimestre')['Faturamento'].sum())

display(faturamento_trimestral)

           Faturamento
Trimestre
2023Q1        25038900
2023Q2        24163700
2023Q3        24970600
2023Q4        25146300

`dt.to_period()`
- 'D' -> para Dias
-'M' -> para meses
- 'Y' -> para anos
- 'Q' -> para trimestres
- 'W' -> para semanas